let tvshowData = [
    {
        title: "13 Reasons Why",
        yearReleased: 2017,
        rating: "Meh",
        showGenre: ["Drama", "Mystery", "Thriller"],
    },
    {
        title: "24",
        yearReleased: 2001,
        rating: "Liked",
        showGenre: ["Action", "Crime", "Drama", "Thriller"],
    },
    {
        title: "30 Rock",
        yearReleased: 2006,
        rating: "Liked",
        showGenre: ["Comedy"],
    },
    {
        title: "About a Boy",
        yearReleased: 2014,
        rating: "Liked",
        showGenre: ["Comedy", "Drama", "Romance"],
    },
    {
        title: "Alias",
        yearReleased: 2001,
        rating: "Loved",
        showGenre: ["Action", "Drama", "Mystery", "Sci-Fi", "Thriller"],
    },
    {
        title: "All That",
        yearReleased: 1994,
        rating: "Meh",
        showGenre: ["Comedy", "Family", "Music"],
    },
    {
        title: "Ally McBeal",
        yearReleased: 1997,
        rating: "Meh",
        showGenre: ["Comedy", "Drama", "Fantasy", "Music", "Romance"],
    },
    {
        title: "America's Best Dance Crew",
        yearReleased: 2008,
        rating: "Meh",
        showGenre: ["Music", "Reality-TV"],
    },
    {
        title: "American Idol",
        yearReleased: 2002,
        rating: "Disliked",
        showGenre: ["Game-Show", "Music", "Reality-TV"],
    },
    {
        title: "Arrested Development",
        yearReleased: 2003,
        rating: "Loved",
        showGenre: ["Comedy"],
    },
    {
        title: "Arrow",
        yearReleased: 2012,
        rating: "Meh",
        showGenre: ["Action", "Adventure", "Crime", "Drama", "Mystery", "Sci-Fi"],
    },
    {
        title: "As Told By Ginger",
        yearReleased: 2000,
        rating: "Liked",
        showGenre: ["Animation", "Comedy", "Drama", "Family"],
    },
    {
        title: "Atlanta",
        yearReleased: 2016,
        rating: "Loved",
        showGenre: ["Comedy", "Drama", "Music"],
    },
    {
        title: "Atypical",
        yearReleased: 2017,
        rating: "Meh",
        showGenre: ["Comedy", "Drama"],
    },
    {
        title: "Barry",
        yearReleased: 2018,
        rating: "Loved",
        showGenre: ["Action", "Comedy", "Crime", "Drama"],
    },
    {
        title: "Best Time Ever with Neil Patrick Harris",
        yearReleased: 2015,
        rating: "Liked",
        showGenre: ["Comedy", "Musical", "Talk-Show", "Game-Show"],
    },
    {
        title: "Better Off Ted",
        yearReleased: 2009,
        rating: "Liked",
        showGenre: ["Comedy", "Sci-Fi"],
    },
    {
        title: "Big Mouth",
        yearReleased: 2017,
        rating: "Meh",
        showGenre: ["Animation", "Comedy", "Romance"],
    },
    {
        title: "Black Books",
        yearReleased: 2000,
        rating: "Liked",
        showGenre: ["Comedy"],
    },
    {
        title: "Black Mirror",
        yearReleased: 2011,
        rating: "Liked",
        showGenre: ["Drama", "Mystery", "Sci-Fi", "Thriller"],
    },
    {
        title: "Bob's Burgers",
        yearReleased: 2011,
        rating: "Liked",
        showGenre: ["Animation", "Comedy"],
    },
    {
        title: "Boy Meets World",
        yearReleased: 1993,
        rating: "Liked",
        showGenre: ["Comedy", "Drama", "Family"],
    },
    {
        title: "Breaking Bad",
        yearReleased: 2008,
        rating: "Loved",
        showGenre: ["Crime", "Drama", "Thriller"],
    },
    {
        title: "Broadchurch",
        yearReleased: 2013,
        rating: "Loved",
        showGenre: ["Crime", "Drama", "Mystery"],
    },
    {
        title: "Brooklyn Nine-Nine",
        yearReleased: 2013,
        rating: "Liked",
        showGenre: ["Comedy", "Crime"],
    },
    {
        title: "Buffy the Vampire Slayer",
        yearReleased: 1997,
        rating: "Liked",
        showGenre: ["Action", "Drama", "Fantasy", "Romance"],
    },
    {
        title: "C.B. Strike",
        yearReleased: 2017,
        rating: "Loved",
        showGenre: ["Crime", "Drama", "Mystery", "Thriller"],
    },
    {
        title: "Castlevania",
        yearReleased: 2017,
        rating: "Meh",
        showGenre: ["Animation", "Action", "Adventure", "Drama", "Fantasy", "Horror"],
    },
    {
        title: "CatDog",
        yearReleased: 1998,
        rating: "Meh",
        showGenre: ["Animation", "Adventure", "Comedy", "Family"],
    },
    {
        title: "Chappelle's Show",
        yearReleased: 2003,
        rating: "Liked",
        showGenre: ["Comedy", "Music"],
    },
    {
        title: "Chilling Adventures of Sabrina",
        yearReleased: 2018,
        rating: "Meh",
        showGenre: ["Drama", "Fantasy", "Horror", "Mystery", "Thriller"],
    },
    {
        title: "Chuck",
        yearReleased: 2007,
        rating: "Loved",
        showGenre: ["Action", "Comedy", "Drama"],
    },
    {
        title: "Community",
        yearReleased: 2009,
        rating: "Loved",
        showGenre: ["Comedy"],
    },
    {
        title: "Coupling",
        yearReleased: 2000,
        rating: "Liked",
        showGenre: ["Comedy", "Romance"],
    },
    {
        title: "Curb Your Enthusiasm",
        yearReleased: 2000,
        rating: "Meh",
        showGenre: ["Comedy"],
    },
    {
        title: "Dash & Lily",
        yearReleased: 2020,
        rating: "Liked",
        showGenre: ["Comedy", "Drama", "Romance"],
    },
    {
        title: "Dear White People",
        yearReleased: 2017,
        rating: "Meh",
        showGenre: ["Comedy", "Drama"],
    },
    {
        title: "Death Note",
        yearReleased: 2006,
        rating: "Liked",
        showGenre: ["Animation", "Crime", "Drama", "Fantasy", "Mystery", "Thriller"],
    },
    {
        title: "Detectorists",
        yearReleased: 2014,
        rating: "Meh",
        showGenre: ["Comedy"],
    },
    {
        title: "Doctor Who",
        yearReleased: 2005,
        rating: "Liked",
        showGenre: ["Adventure", "Drama", "Sci-Fi"],
    },
    {
        title: "Downtown Abbey",
        yearReleased: 2010,
        rating: "Liked",
        showGenre: ["Drama", "Romance"],
    },
    {
        title: "Duck Dynasty",
        yearReleased: 2012,
        rating: "Meh",
        showGenre: ["Comedy", "Reality-TV"],
    },
    {
        title: "Fairly Oddparents",
        yearReleased: 2001,
        rating: "Liked",
        showGenre: ["Action", "Adventure", "Comedy", "Family", "Fantasy"],
    },
    {
        title: "Family Guy",
        yearReleased: 1999,
        rating: "Liked",
        showGenre: ["Animation", "Comedy"],
    },
    {
        title: "Felicity",
        yearReleased: 1998,
        rating: "Meh",
        showGenre: ["Drama", "Romance"],
    },
    {
        title: "Firefly",
        yearReleased: 2002,
        rating: "Liked",
        showGenre: ["Adventure", "Drama", "Sci-Fi"],
    },
    {
        title: "Fleabag",
        yearReleased: 2016,
        rating: "Loved",
        showGenre: ["Comedy", "Drama"],
    },
    {
        title: "Flight of the Conchords",
        yearReleased: 2007,
        rating: "Liked",
        showGenre: ["Comedy", "Music", "Musical"],
    },
    {
        title: "Freaks and Geeks",
        yearReleased: 1999,
        rating: "Liked",
        showGenre: ["Comedy", "Drama"],
    },
    {
        title: "Friends",
        yearReleased: 1994,
        rating: "Loved",
        showGenre: ["Comedy", "Romance"],
    },
    {
        title: "Fringe",
        yearReleased: 2008,
        rating: "Liked",
        showGenre: ["Drama", "Mystery", "Sci-Fi", "Thriller"],
    },
    {
        title: "Full House",
        yearReleased: 1987,
        rating: "Liked",
        showGenre: ["Comedy", "Drama", "Family"],
    },
    {
        title: "Game of Thrones",
        yearReleased: 2011,
        rating: "Liked",
        showGenre: ["Action", "Adventure", "Drama", "Fantasy"],
    },
    {
        title: "Ghosted",
        yearReleased: 2017,
        rating: "Meh",
        showGenre: ["Comedy", "Crime", "Horror", "Mystery", "Sci-Fi", "Thriller"],
    },
    {
        title: "Ghosts",
        yearReleased: 2019,
        rating: "Loved",
        showGenre: ["Comedy", "Fantasy"],
    },
    {
        title: "Glee",
        yearReleased: 2009,
        rating: "Meh",
        showGenre: ["Comedy", "Drama", "Music", "Musical"],
    },
    {
        title: "Goosebumps",
        yearReleased: 1995,
        rating: "Meh",
        showGenre: ["Fantasy", "Horror", "Mystery", "Thriller"],
    },
    {
        title: "Gravity Falls",
        yearReleased: 2012,
        rating: "Liked",
        showGenre: ["Animation", "Action", "Adventure", "Comedy", "Drama", "Family", "Fantasy", "Horror", "Mystery", "Sci-Fi"],
    },
    {
        title: "Halt and Catch Fire",
        yearReleased: 2014,
        rating: "Liked",
        showGenre: ["Drama"],
    },
    {
        title: "Happy Valley",
        yearReleased: 2014,
        rating: "Loved",
        showGenre: ["Crime", "Drama", "Thriller"],
    },
    {
        title: "Heroes",
        yearReleased: 2006,
        rating: "Liked",
        showGenre: ["Drama", "Fantasy", "Sci-Fi", "Thriller"],
    },
    {
        title: "Hey Arnold!",
        yearReleased: 1996,
        rating: "Liked",
        showGenre: ["Animation", "Comedy", "Drama", "Family"],
    },
    {
        title: "Home Movies",
        yearReleased: 1999,
        rating: "Meh",
        showGenre: ["Animation", "Comedy", "Drama"],
    },
    {
        title: "How I Met Your Mother",
        yearReleased: 2005,
        rating: "Liked",
        showGenre: ["Comedy", "Romance"],
    },
    {
        title: "It's Always Sunny in Philadelphia",
        yearReleased: 2005,
        rating: "Loved",
        showGenre: ["Comedy"],
    },
    {
        title: "iZombie",
        yearReleased: 2015,
        rating: "Meh",
        showGenre: ["Comedy", "Crime", "Drama", "Horror"],
    },
    {
        title: "Jackie Chan Adventures",
        yearReleased: 2000,
        rating: "Liked",
        showGenre: ["Animation", "Action", "Adventure", "Comedy", "Family", "Fantasy"],
    },
    {
        title: "Jane the Virgin",
        yearReleased: 2014,
        rating: "Liked",
        showGenre: ["Comedy"],
    },
    {
        title: "Jonathan Strange & Mr Norrell",
        yearReleased: 2015,
        rating: "Liked",
        showGenre: ["Fantasy", "History", "War"],
    },
    {
        title: "Kenan & Kel",
        yearReleased: 1996,
        rating: "Meh",
        showGenre: ["Comedy", "Family"],
    },
    {
        title: "Key & Peele",
        yearReleased: 2012,
        rating: "Liked",
        showGenre: ["Action", "Adventure", "Comedy"],
    },
    {
        title: "Killing Eve",
        yearReleased: 2018,
        rating: "Liked",
        showGenre: ["Action", "Adventure", "Drama", "Thriller"],
    },
    {
        title: "King of the Hill",
        yearReleased: 1997,
        rating: "Liked",
        showGenre: ["Animation", "Comedy", "Drama"],
    },
    {
        title: "Looking for Alaska",
        yearReleased: 2019,
        rating: "Loved",
        showGenre: ["Drama", "Romance"],
    },
    {
        title: "Lost",
        yearReleased: 2004,
        rating: "Loved",
        showGenre: ["Action", "Drama", "Fantasy", "Mystery", "Sci-Fi", "Thriller"],
    },
    {
        title: "Lupin",
        yearReleased: 2021,
        rating: "Loved",
        showGenre: ["Action", "Crime", "Drama", "Mystery"],
    },
    {
        title: "Luther",
        yearReleased: 2010,
        rating: "Liked",
        showGenre: ["Crime", "Drama", "Mystery", "Thriller"],
    },
    {
        title: "Married With Children",
        yearReleased: 1987,
        rating: "Liked",
        showGenre: ["Comedy"],
    },
    {
        title: "Master of None",
        yearReleased: 2015,
        rating: "Liked",
        showGenre: ["Comedy", "Drama"],
    },
    {
        title: "Modern Family",
        yearReleased: 2009,
        rating: "Loved",
        showGenre: ["Comedy", "Drama", "Romance"],
    },
    {
        title: "Most Dangerous Game",
        yearReleased: 2020,
        rating: "Liked",
        showGenre: ["Short", "Action", "Thriller"],
    },
    {
        title: "Mr. Robot",
        yearReleased: 2015,
        rating: "Liked",
        showGenre: ["Crime", "Drama", "Thriller"],
    },
    {
        title: "My Family",
        yearReleased: 2000,
        rating: "Liked",
        showGenre: ["Comedy"],
    },
    {
        title: "My Little Pony: Friendship Is Magic",
        yearReleased: 2010,
        rating: "Meh",
        showGenre: ["Animation", "Adventure", "Comedy", "Drama", "Family", "Fantasy", "Music", "Musical"],
    },
    {
        title: "Mythic Quest",
        yearReleased: 2020,
        rating: "Liked",
        showGenre: ["Comedy"],
    },
    {
        title: "New Girl",
        yearReleased: 2011,
        rating: "Liked",
        showGenre: ["Comedy", "Romance"],
    },
    {
        title: "Once Upon a Time",
        yearReleased: 2011,
        rating: "Meh",
        showGenre: ["Adventure", "Fantasy", "Romance"],
    },
    {
        title: "One of Us is Lying",
        yearReleased: 2021,
        rating: "Liked",
        showGenre: ["Crime", "Drama", "Mystery", "Thriller"],
    },
    {
        title: "One Tree Hill",
        yearReleased: 2003,
        rating: "Liked",
        showGenre: ["Drama", "Romance", "Sport"],
    },
    {
        title: "Only Murders in the Building",
        yearReleased: 2021,
        rating: "Liked",
        showGenre: ["Comedy", "Crime", "Drama", "Mystery", "Thriller"],
    },
    {
        title: "Parks and Recreation",
        yearReleased: 2009,
        rating: "Liked",
        showGenre: ["Comedy"],
    },
    {
        title: "Phineas and Ferb",
        yearReleased: 2007,
        rating: "Liked",
        showGenre: ["Animation", "Short", "Action", "Adventure", "Comedy", "Family", "Musical", "Sci-Fi"],
    },
    {
        title: "Pitch Perfect: Bumper in Berlin",
        yearReleased: 2022,
        rating: "Liked",
        showGenre: ["Comedy"],
    },
    {
        title: "Pokemon",
        yearReleased: 1997,
        rating: "Meh",
        showGenre: ["Animation", "Action", "Adventure", "Comedy", "Family", "Fantasy"],
    },
    {
        title: "Pretty Little Liars",
        yearReleased: 2010,
        rating: "Meh",
        showGenre: ["Drama", "Mystery", "Romance", "Thriller"],
    },
    {
        title: "Psych",
        yearReleased: 2006,
        rating: "Loved",
        showGenre: ["Comedy", "Crime", "Mystery"],
    },
    {
        title: "Punk'd",
        yearReleased: 2003,
        rating: "Liked",
        showGenre: ["Comedy", "Reality-TV"],
    },
    {
        title: "Ramsay's Kitchen Nightmares (UK)",
        yearReleased: 2004,
        rating: "Liked",
        showGenre: ["Reality-TV"],
    },
    {
        title: "Rick and Morty",
        yearReleased: 2013,
        rating: "Loved",
        showGenre: ["Animation", "Adventure", "Comedy", "Sci-Fi"],
    },
    {
        title: "Riverdale",
        yearReleased: 2017,
        rating: "Meh",
        showGenre: ["Crime", "Drama", "Mystery", "Romance"],
    },
    {
        title: "Rocket Power",
        yearReleased: 1999,
        rating: "Meh",
        showGenre: ["Animation", "Action", "Adventure", "Family", "Sport"],
    },
    {
        title: "Rugrats",
        yearReleased: 1991,
        rating: "Liked",
        showGenre: ["Animation", "Adventure", "Comedy", "Family"],
    },
    {
        title: "Sabrina, the Teenage Witch",
        yearReleased: 1996,
        rating: "Meh",
        showGenre: ["Comedy", "Family", "Fantasy"],
    },
    {
        title: "Santa Clarita Diet",
        yearReleased: 2017,
        rating: "Meh",
        showGenre: ["Comedy", "Horror"],
    },
    {
        title: "Saturday Night Live",
        yearReleased: 1975,
        rating: "Liked",
        showGenre: ["Comedy", "Music"],
    },
    {
        title: "Saved by the Bell",
        yearReleased: 1989,
        rating: "Liked",
        showGenre: ["Comedy", "Family", "Romance"],
    },
    {
        title: "Saved by the Bell: The College Years",
        yearReleased: 1993,
        rating: "Liked",
        showGenre: ["Comedy", "Romance"],
    },
    {
        title: "Scare Tactics",
        yearReleased: 2003,
        rating: "Liked",
        showGenre: ["Comedy", "Horror", "Reality-TV", "Sci-Fi", "Thriller"],
    },
    {
        title: "Scooby Doo, Where Are You!",
        yearReleased: 1969,
        rating: "Meh",
        showGenre: ["Animation", "Adventure", "Comedy", "Crime", "Family", "Mystery"],
    },
    {
        title: "Scream Queens",
        yearReleased: 2015,
        rating: "Liked",
        showGenre: ["Comedy", "Horror", "Mystery"],
    },
    {
        title: "Scrubs",
        yearReleased: 2001,
        rating: "Liked",
        showGenre: ["Comedy", "Drama"],
    },
    {
        title: "Seinfeld",
        yearReleased: 1989,
        rating: "Meh",
        showGenre: ["Comedy"],
    },
    {
        title: "Severance",
        yearReleased: 2022,
        rating: "Loved",
        showGenre: ["Drama", "Mystery", "Sci-Fi", "Thriller"],
    },
    {
        title: "Shark Tank",
        yearReleased: 2009,
        rating: "Liked",
        showGenre: ["Family", "Game-Show", "Reality-TV"],
    },
    {
        title: "Sherlock",
        yearReleased: 2010,
        rating: "Liked",
        showGenre: ["Crime", "Drama", "Mystery", "Thriller"],
    },
    {
        title: "Silicon Valley",
        yearReleased: 2014,
        rating: "Liked",
        showGenre: ["Comedy"],
    },
    {
        title: "South Park",
        yearReleased: 1997,
        rating: "Liked",
        showGenre: ["Animation", "Comedy"],
    },
    {
        title: "Spaced",
        yearReleased: 1999,
        rating: "Liked",
        showGenre: ["Action", "Comedy"],
    },
    {
        title: "Spongebob Squarepants",
        yearReleased: 1999,
        rating: "Liked",
        showGenre: ["Animation", "Comedy", "Family", "Fantasy"],
    },
    {
        title: "Squid Game",
        yearReleased: 2021,
        rating: "Liked",
        showGenre: ["Action", "Drama", "Mystery", "Thriller"],
    },
    {
        title: "Stranger Things",
        yearReleased: 2016,
        rating: "Loved",
        showGenre: ["Drama", "Fantasy", "Horror", "Mystery", "Sci-Fi", "Thriller"],
    },
    {
        title: "Succession",
        yearReleased: 2018,
        rating: "Loved",
        showGenre: ["Drama"],
    },
    {
        title: "Supernatural",
        yearReleased: 2005,
        rating: "Liked",
        showGenre: ["Drama", "Fantasy", "Horror", "Mystery", "Thriller"],
    },
    {
        title: "Taskmaster",
        yearReleased: 2015,
        rating: "Loved",
        showGenre: ["Comedy", "Game-Show"],
    },
    {
        title: "Ted Lasso",
        yearReleased: 2020,
        rating: "Loved",
        showGenre: ["Comedy", "Drama", "Sport"],
    },
    {
        title: "Teen Wolf",
        yearReleased: 2011,
        rating: "Meh",
        showGenre: ["Action", "Drama", "Fantasy", "Romance", "Thriller"],
    },
    {
        title: "That 70s Show",
        yearReleased: 1998,
        rating: "Liked",
        showGenre: ["Comedy", "Drama", "Romance"],
    },
    {
        title: "The Adventures of Jimmy Neutron: Boy Genius",
        yearReleased: 2002,
        rating: "Meh",
        showGenre: ["Animation", "Adventure", "Comedy", "Family", "Sci-Fi"],
    },
    {
        title: "The Andy Griffith Show",
        yearReleased: 1960,
        rating: "Liked",
        showGenre: ["Comedy", "Family"],
    },
    {
        title: "The Angry Beavers",
        yearReleased: 1997,
        rating: "Meh",
        showGenre: ["Animation", "Comedy", "Family"],
    },
    {
        title: "The Blacklist",
        yearReleased: 2013,
        rating: "Meh",
        showGenre: ["Crime", "Drama", "Mystery", "Thriller"],
    },
    {
        title: "The Catherine Tate Show ",
        yearReleased: 2004,
        rating: "Liked",
        showGenre: ["Comedy"],
    },
    {
        title: "The Circle",
        yearReleased: 2020,
        rating: "Meh",
        showGenre: ["Game-Show", "Reality-TV"],
    },
    {
        title: "The Cosby Show",
        yearReleased: 1984,
        rating: "Liked",
        showGenre: ["Comedy", "Family", "Romance"],
    },
    {
        title: "The End of the F***ing World",
        yearReleased: 2017,
        rating: "Liked",
        showGenre: ["Adventure", "Comedy", "Crime", "Drama", "Romance", "Thriller"],
    },
    {
        title: "The Fresh Prince of Bel-Air ",
        yearReleased: 1990,
        rating: "Liked",
        showGenre: ["Comedy"],
    },
    {
        title: "The Good Place",
        yearReleased: 2016,
        rating: "Liked",
        showGenre: ["Comedy", "Drama", "Fantasy", "Mystery", "Romance"],
    },
    {
        title: "The Great",
        yearReleased: 2020,
        rating: "Liked",
        showGenre: ["Biography", "Comedy", "Drama", "History"],
    },
    {
        title: "The Great British Baking Show",
        yearReleased: 2010,
        rating: "Liked",
        showGenre: ["Reality-TV"],
    },
    {
        title: "The Guild",
        yearReleased: 2007,
        rating: "Meh",
        showGenre: ["Short", "Comedy"],
    },
    {
        title: "The Inbetweeners",
        yearReleased: 2008,
        rating: "Liked",
        showGenre: ["Comedy"],
    },
    {
        title: "The IT Crowd",
        yearReleased: 2006,
        rating: "Loved",
        showGenre: ["Comedy"],
    },
    {
        title: "The Marvelous Mrs. Maisel",
        yearReleased: 2017,
        rating: "Liked",
        showGenre: ["Comedy", "Drama"],
    },
    {
        title: "The Newsroom",
        yearReleased: 2012,
        rating: "Loved",
        showGenre: ["Drama"],
    },
    {
        title: "The Office (UK)",
        yearReleased: 2001,
        rating: "Liked",
        showGenre: ["Comedy", "Drama"],
    },
    {
        title: "The Office (US)",
        yearReleased: 2005,
        rating: "Loved",
        showGenre: ["Comedy"],
    },
    {
        title: "The Osbournes",
        yearReleased: 2002,
        rating: "Meh",
        showGenre: ["Comedy", "Music", "Reality-TV"],
    },
    {
        title: "The Returned (US)",
        yearReleased: 2015,
        rating: "Liked",
        showGenre: ["Drama", "Fantasy", "Horror"],
    },
    {
        title: "The Simple Life",
        yearReleased: 2003,
        rating: "Disliked",
        showGenre: ["Comedy", "Reality-TV"],
    },
    {
        title: "The Sopranos",
        yearReleased: 1999,
        rating: "Liked",
        showGenre: ["Crime", "Drama"],
    },
    {
        title: "The Summer I Turned Pretty",
        yearReleased: 2022,
        rating: "Liked",
        showGenre: ["Drama", "Romance"],
    },
    {
        title: "The Surreal Life",
        yearReleased: 2003,
        rating: "Meh",
        showGenre: ["Comedy", "Reality-TV"],
    },
    {
        title: "The Vampire Diaries",
        yearReleased: 2009,
        rating: "Liked",
        showGenre: ["Drama", "Fantasy", "Horror", "Mystery", "Romance", "Thriller"],
    },
    {
        title: "The Walking Dead",
        yearReleased: 2010,
        rating: "Liked",
        showGenre: ["Drama", "Horror", "Thriller"],
    },
    {
        title: "The Wild Thornberrys",
        yearReleased: 1998,
        rating: "Meh",
        showGenre: ["Animation", "Adventure", "Comedy", "Family", "Fantasy"],
    },
    {
        title: "The Wire",
        yearReleased: 2002,
        rating: "Liked",
        showGenre: ["Crime", "Drama", "Thriller"],
    },
    {
        title: "Tosh.0",
        yearReleased: 2009,
        rating: "Liked",
        showGenre: ["Comedy"],
    },
    {
        title: "Travel Man: 48 Hours in...",
        yearReleased: 2015,
        rating: "Liked",
        showGenre: ["Documentary", "Adventure", "Comedy"],
    },
    {
        title: "True Blood",
        yearReleased: 2008,
        rating: "Meh",
        showGenre: ["Drama", "Fantasy", "Mystery", "Romance", "Thriller"],
    },
    {
        title: "Unbreakable Kimmy Schmidt",
        yearReleased: 2015,
        rating: "Liked",
        showGenre: ["Comedy"],
    },
    {
        title: "Upload",
        yearReleased: 2020,
        rating: "Liked",
        showGenre: ["Comedy", "Mystery", "Sci-Fi"],
    },
    {
        title: "Veep",
        yearReleased: 2012,
        rating: "Loved",
        showGenre: ["Comedy"],
    },
    {
        title: "Veronica Mars",
        yearReleased: 2019,
        rating: "Loved",
        showGenre: ["Crime", "Drama", "Mystery", "Thriller"],
    },
    {
        title: "Video Game High School",
        yearReleased: 2012,
        rating: "Liked",
        showGenre: ["Action", "Romance", "Sci-Fi"],
    },
    {
        title: "WandaVision",
        yearReleased: 2021,
        rating: "Liked",
        showGenre: ["Action", "Comedy", "Drama", "Fantasy", "Romance", "Sci-Fi"],
    },
    {
        title: "Warehouse 13",
        yearReleased: 2009,
        rating: "Meh",
        showGenre: ["Drama", "Mystery", "Sci-Fi", "Thriller"],
    },
    {
        title: "Wednesday",
        yearReleased: 2022,
        rating: "Loved",
        showGenre: ["Comedy", "Crime", "Family", "Fantasy", "Mystery"],
    },
    {
        title: "What We Do in the Shadows",
        yearReleased: 2019,
        rating: "Liked",
        showGenre: ["Comedy", "Fantasy", "Horror"],
    },
    {
        title: "White Collar",
        yearReleased: 2009,
        rating: "Liked",
        showGenre: ["Comedy", "Crime", "Drama", "Mystery"],
    },
    {
        title: "Whose Line is it Anyway?",
        yearReleased: 1998,
        rating: "Liked",
        showGenre: ["Comedy", "Game-Show"],
    },
    {
        title: "Wilfred (US)",
        yearReleased: 2011,
        rating: "Liked",
        showGenre: ["Comedy", "Drama", "Mystery"],
    },
    {
        title: "Would I Lie To You",
        yearReleased: 2007,
        rating: "Liked",
        showGenre: ["Comedy", "Game-Show"],
    },
    {
        title: "Yu-Gi-Oh!",
        yearReleased: 2000,
        rating: "Meh",
        showGenre: ["Animation", "Action", "Adventure", "Family", "Fantasy"],
    },
];
