let tvshowData = [
  {
    title: "13 Reasons Why",
    yearReleased: 2017,
    episodeCount: 49,
    watchedAll: false,
    rating: 6,
    showGenre: ["Drama", "Mystery", "Thriller"],
  },
  {
    title: "24",
    yearReleased: 2001,
    episodeCount: 195,
    watchedAll: false,
    rating: 7,
    showGenre: ["Action", "Crime", "Drama", "Thriller"],
  },
  {
    title: "30 Rock",
    yearReleased: 2006,
    episodeCount: 138,
    watchedAll: false,
    rating: 7,
    showGenre: ["Comedy"],
  },
  {
    title: "About a Boy",
    yearReleased: 2014,
    episodeCount: 33,
    watchedAll: false,
    rating: 7,
    showGenre: ["Comedy", "Drama", "Romance"],
  },
  {
    title: "Alias",
    yearReleased: 2001,
    episodeCount: 105,
    watchedAll: true,
    rating: 9,
    showGenre: ["Action", "Drama", "Mystery", "Sci-Fi", "Thriller"],
  },
  {
    title: "All That",
    yearReleased: 1994,
    episodeCount: 212,
    watchedAll: false,
    rating: 5,
    showGenre: ["Comedy", "Family", "Music"],
  },
  {
    title: "Ally McBeal",
    yearReleased: 1997,
    episodeCount: 112,
    watchedAll: false,
    rating: 5,
    showGenre: ["Comedy", "Drama", "Fantasy", "Music", "Romance"],
  },
  {
    title: "America's Best Dance Crew",
    yearReleased: 2008,
    episodeCount: 86,
    watchedAll: false,
    rating: 5,
    showGenre: ["Music", "Reality-TV"],
  },
  {
    title: "American Idol",
    yearReleased: 2002,
    episodeCount: 674,
    watchedAll: false,
    rating: 4,
    showGenre: ["Game-Show", "Music", "Reality-TV"],
  },
  {
    title: "Arrested Development",
    yearReleased: 2003,
    episodeCount: 84,
    watchedAll: false,
    rating: 9,
    showGenre: ["Comedy"],
  },
  {
    title: "Arrow",
    yearReleased: 2012,
    episodeCount: 170,
    watchedAll: false,
    rating: 6,
    showGenre: ["Action", "Adventure", "Crime", "Drama", "Mystery", "Sci-Fi"],
  },
  {
    title: "As Told By Ginger",
    yearReleased: 2000,
    episodeCount: 54,
    watchedAll: false,
    rating: 7,
    showGenre: ["Animation", "Comedy", "Drama", "Family"],
  },
  {
    title: "Atlanta",
    yearReleased: 2016,
    episodeCount: 41,
    watchedAll: true,
    rating: 10,
    showGenre: ["Comedy", "Drama", "Music"],
  },
  {
    title: "Atypical",
    yearReleased: 2017,
    episodeCount: 38,
    watchedAll: false,
    rating: 6,
    showGenre: ["Comedy", "Drama"],
  },
  {
    title: "Barry",
    yearReleased: 2018,
    episodeCount: 27,
    watchedAll: false,
    rating: 10,
    showGenre: ["Action", "Comedy", "Crime", "Drama"],
  },
  {
    title: "Best Time Ever with Neil Patrick Harris",
    yearReleased: 2015,
    episodeCount: 8,
    watchedAll: true,
    rating: 7,
    showGenre: ["Comedy", "Musical", "Talk-Show", "Game-Show"],
  },
  {
    title: "Better Off Ted",
    yearReleased: 2009,
    episodeCount: 26,
    watchedAll: true,
    rating: 7,
    showGenre: ["Comedy", "Sci-Fi"],
  },
  {
    title: "Big Mouth",
    yearReleased: 2017,
    episodeCount: 62,
    watchedAll: false,
    rating: 6,
    showGenre: ["Animation", "Comedy", "Romance"],
  },
  {
    title: "Black Books",
    yearReleased: 2000,
    episodeCount: 18,
    watchedAll: true,
    rating: 8,
    showGenre: ["Comedy"],
  },
  {
    title: "Black Mirror",
    yearReleased: 2011,
    episodeCount: 23,
    watchedAll: false,
    rating: 7,
    showGenre: ["Drama", "Mystery", "Sci-Fi", "Thriller"],
  },
  {
    title: "Bob's Burgers",
    yearReleased: 2011,
    episodeCount: 247,
    watchedAll: false,
    rating: 8,
    showGenre: ["Animation", "Comedy"],
  },
  {
    title: "Boy Meets World",
    yearReleased: 1993,
    episodeCount: 158,
    watchedAll: false,
    rating: 7,
    showGenre: ["Comedy", "Drama", "Family"],
  },
  {
    title: "Breaking Bad",
    yearReleased: 2008,
    episodeCount: 62,
    watchedAll: true,
    rating: 9,
    showGenre: ["Crime", "Drama", "Thriller"],
  },
  {
    title: "Broadchurch",
    yearReleased: 2013,
    episodeCount: 24,
    watchedAll: true,
    rating: 9,
    showGenre: ["Crime", "Drama", "Mystery"],
  },
  {
    title: "Brooklyn Nine-Nine",
    yearReleased: 2013,
    episodeCount: 153,
    watchedAll: false,
    rating: 7,
    showGenre: ["Comedy", "Crime"],
  },
  {
    title: "Buffy the Vampire Slayer",
    yearReleased: 1997,
    episodeCount: 145,
    watchedAll: true,
    rating: 8,
    showGenre: ["Action", "Drama", "Fantasy", "Romance"],
  },
  {
    title: "C.B. Strike",
    yearReleased: 2017,
    episodeCount: 15,
    watchedAll: false,
    rating: 9,
    showGenre: ["Crime", "Drama", "Mystery", "Thriller"],
  },
  {
    title: "Castlevania",
    yearReleased: 2017,
    episodeCount: 32,
    watchedAll: false,
    rating: 6,
    showGenre: ["Animation", "Action", "Adventure", "Drama", "Fantasy", "Horror"],
  },
  {
    title: "CatDog",
    yearReleased: 1998,
    episodeCount: 67,
    watchedAll: false,
    rating: 6,
    showGenre: ["Animation", "Adventure", "Comedy", "Family"],
  },
  {
    title: "Chappelle's Show",
    yearReleased: 2003,
    episodeCount: 33,
    watchedAll: false,
    rating: 8,
    showGenre: ["Comedy", "Music"],
  },
  {
    title: "Chilling Adventures of Sabrina",
    yearReleased: 2018,
    episodeCount: 36,
    watchedAll: false,
    rating: 5,
    showGenre: ["Drama", "Fantasy", "Horror", "Mystery", "Thriller"],
  },
  {
    title: "Chuck",
    yearReleased: 2007,
    episodeCount: 91,
    watchedAll: true,
    rating: 10,
    showGenre: ["Action", "Comedy", "Drama"],
  },
  {
    title: "Community",
    yearReleased: 2009,
    episodeCount: 110,
    watchedAll: true,
    rating: 9,
    showGenre: ["Comedy"],
  },
  {
    title: "Coupling",
    yearReleased: 2000,
    episodeCount: 28,
    watchedAll: true,
    rating: 7,
    showGenre: ["Comedy", "Romance"],
  },
  {
    title: "Curb Your Enthusiasm",
    yearReleased: 2000,
    episodeCount: 111,
    watchedAll: false,
    rating: 6,
    showGenre: ["Comedy"],
  },
  {
    title: "Dash & Lily",
    yearReleased: 2020,
    episodeCount: 8,
    watchedAll: true,
    rating: 7,
    showGenre: ["Comedy", "Drama", "Romance"],
  },
  {
    title: "Dear White People",
    yearReleased: 2017,
    episodeCount: 40,
    watchedAll: false,
    rating: 5,
    showGenre: ["Comedy", "Drama"],
  },
  {
    title: "Death Note",
    yearReleased: 2006,
    episodeCount: 37,
    watchedAll: true,
    rating: 7,
    showGenre: ["Animation", "Crime", "Drama", "Fantasy", "Mystery", "Thriller"],
  },
  {
    title: "Detectorists",
    yearReleased: 2014,
    episodeCount: 20,
    watchedAll: false,
    rating: 6,
    showGenre: ["Comedy"],
  },
  {
    title: "Doctor Who",
    yearReleased: 2005,
    episodeCount: 201,
    watchedAll: false,
    rating: 8,
    showGenre: ["Adventure", "Drama", "Sci-Fi"],
  },
  {
    title: "Downtown Abbey",
    yearReleased: 2010,
    episodeCount: 52,
    watchedAll: false,
    rating: 8,
    showGenre: ["Drama", "Romance"],
  },
  {
    title: "Duck Dynasty",
    yearReleased: 2012,
    episodeCount: 132,
    watchedAll: false,
    rating: 5,
    showGenre: ["Comedy", "Reality-TV"],
  },
  {
    title: "Fairly Oddparents",
    yearReleased: 2001,
    episodeCount: 159,
    watchedAll: false,
    rating: 7,
    showGenre: ["Action", "Adventure", "Comedy", "Family", "Fantasy"],
  },
  {
    title: "Family Guy",
    yearReleased: 1999,
    episodeCount: 399,
    watchedAll: false,
    rating: 7,
    showGenre: ["Animation", "Comedy"],
  },
  {
    title: "Felicity",
    yearReleased: 1998,
    episodeCount: 84,
    watchedAll: true,
    rating: 6,
    showGenre: ["Drama", "Romance"],
  },
  {
    title: "Firefly",
    yearReleased: 2002,
    episodeCount: 14,
    watchedAll: true,
    rating: 8,
    showGenre: ["Adventure", "Drama", "Sci-Fi"],
  },
  {
    title: "Fleabag",
    yearReleased: 2016,
    episodeCount: 12,
    watchedAll: true,
    rating: 9,
    showGenre: ["Comedy", "Drama"],
  },
  {
    title: "Flight of the Conchords",
    yearReleased: 2007,
    episodeCount: 22,
    watchedAll: true,
    rating: 7,
    showGenre: ["Comedy", "Music", "Musical"],
  },
  {
    title: "Freaks and Geeks",
    yearReleased: 1999,
    episodeCount: 18,
    watchedAll: true,
    rating: 8,
    showGenre: ["Comedy", "Drama"],
  },
  {
    title: "Friends",
    yearReleased: 1994,
    episodeCount: 235,
    watchedAll: true,
    rating: 9,
    showGenre: ["Comedy", "Romance"],
  },
  {
    title: "Fringe",
    yearReleased: 2008,
    episodeCount: 100,
    watchedAll: true,
    rating: 7,
    showGenre: ["Drama", "Mystery", "Sci-Fi", "Thriller"],
  },
  {
    title: "Full House",
    yearReleased: 1987,
    episodeCount: 193,
    watchedAll: false,
    rating: 7,
    showGenre: ["Comedy", "Drama", "Family"],
  },
  {
    title: "Game of Thrones",
    yearReleased: 2011,
    episodeCount: 73,
    watchedAll: true,
    rating: 7,
    showGenre: ["Action", "Adventure", "Drama", "Fantasy"],
  },
  {
    title: "Ghosted",
    yearReleased: 2017,
    episodeCount: 16,
    watchedAll: false,
    rating: 6,
    showGenre: ["Comedy", "Crime", "Horror", "Mystery", "Sci-Fi", "Thriller"],
  },
  {
    title: "Ghosts",
    yearReleased: 2019,
    episodeCount: 33,
    watchedAll: false,
    rating: 9,
    showGenre: ["Comedy", "Fantasy"],
  },
  {
    title: "Glee",
    yearReleased: 2009,
    episodeCount: 121,
    watchedAll: false,
    rating: 5,
    showGenre: ["Comedy", "Drama", "Music", "Musical"],
  },
  {
    title: "Goosebumps",
    yearReleased: 1995,
    episodeCount: 74,
    watchedAll: false,
    rating: 5,
    showGenre: ["Fantasy", "Horror", "Mystery", "Thriller"],
  },
  {
    title: "Gravity Falls",
    yearReleased: 2012,
    episodeCount: 40,
    watchedAll: true,
    rating: 8,
    showGenre: ["Animation", "Action", "Adventure", "Comedy", "Drama", "Family", "Fantasy", "Horror", "Mystery", "Sci-Fi"],
  },
  {
    title: "Halt and Catch Fire",
    yearReleased: 2014,
    episodeCount: 40,
    watchedAll: true,
    rating: 7,
    showGenre: ["Drama"],
  },
  {
    title: "Happy Valley",
    yearReleased: 2014,
    episodeCount: 18,
    watchedAll: false,
    rating: 9,
    showGenre: ["Crime", "Drama", "Thriller"],
  },
  {
    title: "Heroes",
    yearReleased: 2006,
    episodeCount: 78,
    watchedAll: false,
    rating: 7,
    showGenre: ["Drama", "Fantasy", "Sci-Fi", "Thriller"],
  },
  {
    title: "Hey Arnold!",
    yearReleased: 1996,
    episodeCount: 103,
    watchedAll: true,
    rating: 7,
    showGenre: ["Animation", "Comedy", "Drama", "Family"],
  },
  {
    title: "Home Movies",
    yearReleased: 1999,
    episodeCount: 52,
    watchedAll: false,
    rating: 6,
    showGenre: ["Animation", "Comedy", "Drama"],
  },
  {
    title: "How I Met Your Mother",
    yearReleased: 2005,
    episodeCount: 208,
    watchedAll: true,
    rating: 8,
    showGenre: ["Comedy", "Romance"],
  },
  {
    title: "It's Always Sunny in Philadelphia",
    yearReleased: 2005,
    episodeCount: 165,
    watchedAll: false,
    rating: 9,
    showGenre: ["Comedy"],
  },
  {
    title: "iZombie",
    yearReleased: 2015,
    episodeCount: 71,
    watchedAll: false,
    rating: 6,
    showGenre: ["Comedy", "Crime", "Drama", "Horror"],
  },
  {
    title: "Jackie Chan Adventures",
    yearReleased: 2000,
    episodeCount: 95,
    watchedAll: true,
    rating: 7,
    showGenre: ["Animation", "Action", "Adventure", "Comedy", "Family", "Fantasy"],
  },
  {
    title: "Jane the Virgin",
    yearReleased: 2014,
    episodeCount: 100,
    watchedAll: false,
    rating: 7,
    showGenre: ["Comedy"],
  },
  {
    title: "Jonathan Strange & Mr Norrell",
    yearReleased: 2015,
    episodeCount: 7,
    watchedAll: true,
    rating: 7,
    showGenre: ["Fantasy", "History", "War"],
  },
  {
    title: "Kenan & Kel",
    yearReleased: 1996,
    episodeCount: 62,
    watchedAll: false,
    rating: 6,
    showGenre: ["Comedy", "Family"],
  },
  {
    title: "Key & Peele",
    yearReleased: 2012,
    episodeCount: 55,
    watchedAll: false,
    rating: 8,
    showGenre: ["Action", "Adventure", "Comedy"],
  },
  {
    title: "Killing Eve",
    yearReleased: 2018,
    episodeCount: 32,
    watchedAll: false,
    rating: 8,
    showGenre: ["Action", "Adventure", "Drama", "Thriller"],
  },
  {
    title: "King of the Hill",
    yearReleased: 1997,
    episodeCount: 258,
    watchedAll: false,
    rating: 8,
    showGenre: ["Animation", "Comedy", "Drama"],
  },
  {
    title: "Looking for Alaska",
    yearReleased: 2019,
    episodeCount: 8,
    watchedAll: true,
    rating: 9,
    showGenre: ["Drama", "Romance"],
  },
  {
    title: "Lost",
    yearReleased: 2004,
    episodeCount: 120,
    watchedAll: true,
    rating: 10,
    showGenre: ["Action", "Drama", "Fantasy", "Mystery", "Sci-Fi", "Thriller"],
  },
  {
    title: "Lupin",
    yearReleased: 2021,
    episodeCount: 11,
    watchedAll: false,
    rating: 9,
    showGenre: ["Action", "Crime", "Drama", "Mystery"],
  },
  {
    title: "Luther",
    yearReleased: 2010,
    episodeCount: 21,
    watchedAll: false,
    rating: 8,
    showGenre: ["Crime", "Drama", "Mystery", "Thriller"],
  },
  {
    title: "Married With Children",
    yearReleased: 1987,
    episodeCount: 262,
    watchedAll: false,
    rating: 7,
    showGenre: ["Comedy"],
  },
  {
    title: "Master of None",
    yearReleased: 2015,
    episodeCount: 25,
    watchedAll: false,
    rating: 8,
    showGenre: ["Comedy", "Drama"],
  },
  {
    title: "Modern Family",
    yearReleased: 2009,
    episodeCount: 250,
    watchedAll: true,
    rating: 9,
    showGenre: ["Comedy", "Drama", "Romance"],
  },
  {
    title: "Most Dangerous Game",
    yearReleased: 2020,
    episodeCount: 23,
    watchedAll: true,
    rating: 7,
    showGenre: ["Short", "Action", "Thriller"],
  },
  {
    title: "Mr. Robot",
    yearReleased: 2015,
    episodeCount: 45,
    watchedAll: false,
    rating: 7,
    showGenre: ["Crime", "Drama", "Thriller"],
  },
  {
    title: "My Family",
    yearReleased: 2000,
    episodeCount: 121,
    watchedAll: false,
    rating: 8,
    showGenre: ["Comedy"],
  },
  {
    title: "My Little Pony: Friendship Is Magic",
    yearReleased: 2010,
    episodeCount: 235,
    watchedAll: false,
    rating: 6,
    showGenre: ["Animation", "Adventure", "Comedy", "Drama", "Family", "Fantasy", "Music", "Musical"],
  },
  {
    title: "Mythic Quest",
    yearReleased: 2020,
    episodeCount: 31,
    watchedAll: false,
    rating: 8,
    showGenre: ["Comedy"],
  },
  {
    title: "New Girl",
    yearReleased: 2011,
    episodeCount: 146,
    watchedAll: true,
    rating: 8,
    showGenre: ["Comedy", "Romance"],
  },
  {
    title: "Once Upon a Time",
    yearReleased: 2011,
    episodeCount: 156,
    watchedAll: false,
    rating: 6,
    showGenre: ["Adventure", "Fantasy", "Romance"],
  },
  {
    title: "One of Us is Lying",
    yearReleased: 2021,
    episodeCount: 16,
    watchedAll: false,
    rating: 8,
    showGenre: ["Crime", "Drama", "Mystery", "Thriller"],
  },
  {
    title: "One Tree Hill",
    yearReleased: 2003,
    episodeCount: 187,
    watchedAll: false,
    rating: 8,
    showGenre: ["Drama", "Romance", "Sport"],
  },
  {
    title: "Only Murders in the Building",
    yearReleased: 2021,
    episodeCount: 21,
    watchedAll: false,
    rating: 8,
    showGenre: ["Comedy", "Crime", "Drama", "Mystery", "Thriller"],
  },
  {
    title: "Parks and Recreation",
    yearReleased: 2009,
    episodeCount: 124,
    watchedAll: true,
    rating: 8,
    showGenre: ["Comedy"],
  },
  {
    title: "Phineas and Ferb",
    yearReleased: 2007,
    episodeCount: 130,
    watchedAll: false,
    rating: 8,
    showGenre: ["Animation", "Short", "Action", "Adventure", "Comedy", "Family", "Musical", "Sci-Fi"],
  },
  {
    title: "Pitch Perfect: Bumper in Berlin",
    yearReleased: 2022,
    episodeCount: 6,
    watchedAll: false,
    rating: 8,
    showGenre: ["Comedy"],
  },
  {
    title: "Pokemon",
    yearReleased: 1997,
    episodeCount: 1200,
    watchedAll: false,
    rating: 6,
    showGenre: ["Animation", "Action", "Adventure", "Comedy", "Family", "Fantasy"],
  },
  {
    title: "Pretty Little Liars",
    yearReleased: 2010,
    episodeCount: 161,
    watchedAll: false,
    rating: 6,
    showGenre: ["Drama", "Mystery", "Romance", "Thriller"],
  },
  {
    title: "Psych",
    yearReleased: 2006,
    episodeCount: 121,
    watchedAll: true,
    rating: 10,
    showGenre: ["Comedy", "Crime", "Mystery"],
  },
  {
    title: "Punk'd",
    yearReleased: 2003,
    episodeCount: 148,
    watchedAll: false,
    rating: 7,
    showGenre: ["Comedy", "Reality-TV"],
  },
  {
    title: "Ramsay's Kitchen Nightmares (UK)",
    yearReleased: 2004,
    episodeCount: 33,
    watchedAll: false,
    rating: 7,
    showGenre: ["Reality-TV"],
  },
  {
    title: "Rick and Morty",
    yearReleased: 2013,
    episodeCount: 61,
    watchedAll: false,
    rating: 10,
    showGenre: ["Animation", "Adventure", "Comedy", "Sci-Fi"],
  },
  {
    title: "Riverdale",
    yearReleased: 2017,
    episodeCount: 118,
    watchedAll: false,
    rating: 5,
    showGenre: ["Crime", "Drama", "Mystery", "Romance"],
  },
  {
    title: "Rocket Power",
    yearReleased: 1999,
    episodeCount: 65,
    watchedAll: false,
    rating: 6,
    showGenre: ["Animation", "Action", "Adventure", "Family", "Sport"],
  },
  {
    title: "Rugrats",
    yearReleased: 1991,
    episodeCount: 178,
    watchedAll: true,
    rating: 7,
    showGenre: ["Animation", "Adventure", "Comedy", "Family"],
  },
  {
    title: "Sabrina, the Teenage Witch",
    yearReleased: 1996,
    episodeCount: 163,
    watchedAll: false,
    rating: 6,
    showGenre: ["Comedy", "Family", "Fantasy"],
  },
  {
    title: "Santa Clarita Diet",
    yearReleased: 2017,
    episodeCount: 30,
    watchedAll: false,
    rating: 6,
    showGenre: ["Comedy", "Horror"],
  },
  {
    title: "Saturday Night Live",
    yearReleased: 1975,
    episodeCount: 941,
    watchedAll: false,
    rating: 7,
    showGenre: ["Comedy", "Music"],
  },
  {
    title: "Saved by the Bell",
    yearReleased: 1989,
    episodeCount: 86,
    watchedAll: true,
    rating: 7,
    showGenre: ["Comedy", "Family", "Romance"],
  },
  {
    title: "Saved by the Bell: The College Years",
    yearReleased: 1993,
    episodeCount: 19,
    watchedAll: true,
    rating: 7,
    showGenre: ["Comedy", "Romance"],
  },
  {
    title: "Scare Tactics",
    yearReleased: 2003,
    episodeCount: 151,
    watchedAll: false,
    rating: 7,
    showGenre: ["Comedy", "Horror", "Reality-TV", "Sci-Fi", "Thriller"],
  },
  {
    title: "Scooby Doo, Where Are You!",
    yearReleased: 1969,
    episodeCount: 25,
    watchedAll: true,
    rating: 6,
    showGenre: ["Animation", "Adventure", "Comedy", "Crime", "Family", "Mystery"],
  },
  {
    title: "Scream Queens",
    yearReleased: 2015,
    episodeCount: 23,
    watchedAll: true,
    rating: 7,
    showGenre: ["Comedy", "Horror", "Mystery"],
  },
  {
    title: "Scrubs",
    yearReleased: 2001,
    episodeCount: 182,
    watchedAll: true,
    rating: 8,
    showGenre: ["Comedy", "Drama"],
  },
  {
    title: "Seinfeld",
    yearReleased: 1989,
    episodeCount: 173,
    watchedAll: false,
    rating: 6,
    showGenre: ["Comedy"],
  },
  {
    title: "Severance",
    yearReleased: 2022,
    episodeCount: 19,
    watchedAll: false,
    rating: 9,
    showGenre: ["Drama", "Mystery", "Sci-Fi", "Thriller"],
  },
  {
    title: "Shark Tank",
    yearReleased: 2009,
    episodeCount: 307,
    watchedAll: false,
    rating: 8,
    showGenre: ["Family", "Game-Show", "Reality-TV"],
  },
  {
    title: "Sherlock",
    yearReleased: 2010,
    episodeCount: 15,
    watchedAll: false,
    rating: 8,
    showGenre: ["Crime", "Drama", "Mystery", "Thriller"],
  },
  {
    title: "Silicon Valley",
    yearReleased: 2014,
    episodeCount: 53,
    watchedAll: true,
    rating: 8,
    showGenre: ["Comedy"],
  },
  {
    title: "South Park",
    yearReleased: 1997,
    episodeCount: 320,
    watchedAll: false,
    rating: 7,
    showGenre: ["Animation", "Comedy"],
  },
  {
    title: "Spaced",
    yearReleased: 1999,
    episodeCount: 14,
    watchedAll: true,
    rating: 7,
    showGenre: ["Action", "Comedy"],
  },
  {
    title: "Spongebob Squarepants",
    yearReleased: 1999,
    episodeCount: 305,
    watchedAll: false,
    rating: 7,
    showGenre: ["Animation", "Comedy", "Family", "Fantasy"],
  },
  {
    title: "Squid Game",
    yearReleased: 2021,
    episodeCount: 10,
    watchedAll: false,
    rating: 7,
    showGenre: ["Action", "Drama", "Mystery", "Thriller"],
  },
  {
    title: "Stranger Things",
    yearReleased: 2016,
    episodeCount: 42,
    watchedAll: false,
    rating: 10,
    showGenre: ["Drama", "Fantasy", "Horror", "Mystery", "Sci-Fi", "Thriller"],
  },
  {
    title: "Succession",
    yearReleased: 2018,
    episodeCount: 39,
    watchedAll: false,
    rating: 9,
    showGenre: ["Drama"],
  },
  {
    title: "Supernatural",
    yearReleased: 2005,
    episodeCount: 327,
    watchedAll: false,
    rating: 7,
    showGenre: ["Drama", "Fantasy", "Horror", "Mystery", "Thriller"],
  },
  {
    title: "Taskmaster",
    yearReleased: 2015,
    episodeCount: 139,
    watchedAll: false,
    rating: 9,
    showGenre: ["Comedy", "Game-Show"],
  },
  {
    title: "Ted Lasso",
    yearReleased: 2020,
    episodeCount: 34,
    watchedAll: false,
    rating: 10,
    showGenre: ["Comedy", "Drama", "Sport"],
  },
  {
    title: "Teen Wolf",
    yearReleased: 2011,
    episodeCount: 100,
    watchedAll: false,
    rating: 6,
    showGenre: ["Action", "Drama", "Fantasy", "Romance", "Thriller"],
  },
  {
    title: "That 70s Show",
    yearReleased: 1998,
    episodeCount: 200,
    watchedAll: true,
    rating: 7,
    showGenre: ["Comedy", "Drama", "Romance"],
  },
  {
    title: "The Adventures of Jimmy Neutron: Boy Genius",
    yearReleased: 2002,
    episodeCount: 59,
    watchedAll: false,
    rating: 5,
    showGenre: ["Animation", "Adventure", "Comedy", "Family", "Sci-Fi"],
  },
  {
    title: "The Andy Griffith Show",
    yearReleased: 1960,
    episodeCount: 249,
    watchedAll: false,
    rating: 7,
    showGenre: ["Comedy", "Family"],
  },
  {
    title: "The Angry Beavers",
    yearReleased: 1997,
    episodeCount: 64,
    watchedAll: false,
    rating: 5,
    showGenre: ["Animation", "Comedy", "Family"],
  },
  {
    title: "The Blacklist",
    yearReleased: 2013,
    episodeCount: 198,
    watchedAll: false,
    rating: 6,
    showGenre: ["Crime", "Drama", "Mystery", "Thriller"],
  },
  {
    title: "The Catherine Tate Show ",
    yearReleased: 2004,
    episodeCount: 23,
    watchedAll: false,
    rating: 7,
    showGenre: ["Comedy"],
  },
  {
    title: "The Circle",
    yearReleased: 2020,
    episodeCount: 52,
    watchedAll: false,
    rating: 5,
    showGenre: ["Game-Show", "Reality-TV"],
  },
  {
    title: "The Cosby Show",
    yearReleased: 1984,
    episodeCount: 197,
    watchedAll: true,
    rating: 8,
    showGenre: ["Comedy", "Family", "Romance"],
  },
  {
    title: "The End of the F***ing World",
    yearReleased: 2017,
    episodeCount: 16,
    watchedAll: true,
    rating: 8,
    showGenre: ["Adventure", "Comedy", "Crime", "Drama", "Romance", "Thriller"],
  },
  {
    title: "The Fresh Prince of Bel-Air ",
    yearReleased: 1990,
    episodeCount: 148,
    watchedAll: false,
    rating: 7,
    showGenre: ["Comedy"],
  },
  {
    title: "The Good Place",
    yearReleased: 2016,
    episodeCount: 50,
    watchedAll: false,
    rating: 7,
    showGenre: ["Comedy", "Drama", "Fantasy", "Mystery", "Romance"],
  },
  {
    title: "The Great",
    yearReleased: 2020,
    episodeCount: 30,
    watchedAll: false,
    rating: 7,
    showGenre: ["Biography", "Comedy", "Drama", "History"],
  },
  {
    title: "The Great British Baking Show",
    yearReleased: 2010,
    episodeCount: 165,
    watchedAll: false,
    rating: 7,
    showGenre: ["Reality-TV"],
  },
  {
    title: "The Guild",
    yearReleased: 2007,
    episodeCount: 73,
    watchedAll: true,
    rating: 6,
    showGenre: ["Short", "Comedy"],
  },
  {
    title: "The Inbetweeners",
    yearReleased: 2008,
    episodeCount: 18,
    watchedAll: true,
    rating: 7,
    showGenre: ["Comedy"],
  },
  {
    title: "The IT Crowd",
    yearReleased: 2006,
    episodeCount: 25,
    watchedAll: true,
    rating: 10,
    showGenre: ["Comedy"],
  },
  {
    title: "The Marvelous Mrs. Maisel",
    yearReleased: 2017,
    episodeCount: 35,
    watchedAll: false,
    rating: 7,
    showGenre: ["Comedy", "Drama"],
  },
  {
    title: "The Newsroom",
    yearReleased: 2012,
    episodeCount: 25,
    watchedAll: true,
    rating: 9,
    showGenre: ["Drama"],
  },
  {
    title: "The Office (UK)",
    yearReleased: 2001,
    episodeCount: 14,
    watchedAll: true,
    rating: 8,
    showGenre: ["Comedy", "Drama"],
  },
  {
    title: "The Office (US)",
    yearReleased: 2005,
    episodeCount: 188,
    watchedAll: true,
    rating: 10,
    showGenre: ["Comedy"],
  },
  {
    title: "The Osbournes",
    yearReleased: 2002,
    episodeCount: 52,
    watchedAll: false,
    rating: 5,
    showGenre: ["Comedy", "Music", "Reality-TV"],
  },
  {
    title: "The Returned (US)",
    yearReleased: 2015,
    episodeCount: 10,
    watchedAll: true,
    rating: 7,
    showGenre: ["Drama", "Fantasy", "Horror"],
  },
  {
    title: "The Simple Life",
    yearReleased: 2003,
    episodeCount: 56,
    watchedAll: false,
    rating: 4,
    showGenre: ["Comedy", "Reality-TV"],
  },
  {
    title: "The Sopranos",
    yearReleased: 1999,
    episodeCount: 86,
    watchedAll: false,
    rating: 7,
    showGenre: ["Crime", "Drama"],
  },
  {
    title: "The Summer I Turned Pretty",
    yearReleased: 2022,
    episodeCount: 9,
    watchedAll: false,
    rating: 7,
    showGenre: ["Drama", "Romance"],
  },
  {
    title: "The Surreal Life",
    yearReleased: 2003,
    episodeCount: 68,
    watchedAll: false,
    rating: 5,
    showGenre: ["Comedy", "Reality-TV"],
  },
  {
    title: "The Vampire Diaries",
    yearReleased: 2009,
    episodeCount: 171,
    watchedAll: true,
    rating: 7,
    showGenre: ["Drama", "Fantasy", "Horror", "Mystery", "Romance", "Thriller"],
  },
  {
    title: "The Walking Dead",
    yearReleased: 2010,
    episodeCount: 177,
    watchedAll: false,
    rating: 7,
    showGenre: ["Drama", "Horror", "Thriller"],
  },
  {
    title: "The Wild Thornberrys",
    yearReleased: 1998,
    episodeCount: 93,
    watchedAll: false,
    rating: 6,
    showGenre: ["Animation", "Adventure", "Comedy", "Family", "Fantasy"],
  },
  {
    title: "The Wire",
    yearReleased: 2002,
    episodeCount: 60,
    watchedAll: false,
    rating: 8,
    showGenre: ["Crime", "Drama", "Thriller"],
  },
  {
    title: "Tosh.0",
    yearReleased: 2009,
    episodeCount: 304,
    watchedAll: false,
    rating: 8,
    showGenre: ["Comedy"],
  },
  {
    title: "Travel Man: 48 Hours in...",
    yearReleased: 2015,
    episodeCount: 52,
    watchedAll: false,
    rating: 8,
    showGenre: ["Documentary", "Adventure", "Comedy"],
  },
  {
    title: "True Blood",
    yearReleased: 2008,
    episodeCount: 81,
    watchedAll: false,
    rating: 6,
    showGenre: ["Drama", "Fantasy", "Mystery", "Romance", "Thriller"],
  },
  {
    title: "Unbreakable Kimmy Schmidt",
    yearReleased: 2015,
    episodeCount: 52,
    watchedAll: false,
    rating: 7,
    showGenre: ["Comedy"],
  },
  {
    title: "Upload",
    yearReleased: 2020,
    episodeCount: 18,
    watchedAll: false,
    rating: 7,
    showGenre: ["Comedy", "Mystery", "Sci-Fi"],
  },
  {
    title: "Veep",
    yearReleased: 2012,
    episodeCount: 65,
    watchedAll: true,
    rating: 9,
    showGenre: ["Comedy"],
  },
  {
    title: "Veronica Mars",
    yearReleased: 2019,
    episodeCount: 72,
    watchedAll: true,
    rating: 9,
    showGenre: ["Crime", "Drama", "Mystery", "Thriller"],
  },
  {
    title: "Video Game High School",
    yearReleased: 2012,
    episodeCount: 21,
    watchedAll: true,
    rating: 7,
    showGenre: ["Action", "Romance", "Sci-Fi"],
  },
  {
    title: "WandaVision",
    yearReleased: 2021,
    episodeCount: 9,
    watchedAll: true,
    rating: 8,
    showGenre: ["Action", "Comedy", "Drama", "Fantasy", "Romance", "Sci-Fi"],
  },
  {
    title: "Warehouse 13",
    yearReleased: 2009,
    episodeCount: 64,
    watchedAll: false,
    rating: 6,
    showGenre: ["Drama", "Mystery", "Sci-Fi", "Thriller"],
  },
  {
    title: "Wednesday",
    yearReleased: 2022,
    episodeCount: 8,
    watchedAll: false,
    rating: 10,
    showGenre: ["Comedy", "Crime", "Family", "Fantasy", "Mystery"],
  },
  {
    title: "What We Do in the Shadows",
    yearReleased: 2019,
    episodeCount: 42,
    watchedAll: false,
    rating: 7,
    showGenre: ["Comedy", "Fantasy", "Horror"],
  },
  {
    title: "White Collar",
    yearReleased: 2009,
    episodeCount: 81,
    watchedAll: false,
    rating: 7,
    showGenre: ["Comedy", "Crime", "Drama", "Mystery"],
  },
  {
    title: "Whose Line is it Anyway?",
    yearReleased: 1998,
    episodeCount: 220,
    watchedAll: false,
    rating: 7,
    showGenre: ["Comedy", "Game-Show"],
  },
  {
    title: "Wilfred (US)",
    yearReleased: 2011,
    episodeCount: 49,
    watchedAll: false,
    rating: 7,
    showGenre: ["Comedy", "Drama", "Mystery"],
  },
  {
    title: "Would I Lie To You",
    yearReleased: 2007,
    episodeCount: 159,
    watchedAll: false,
    rating: 8,
    showGenre: ["Comedy", "Game-Show"],
  },
  {
    title: "Yu-Gi-Oh!",
    yearReleased: 2000,
    episodeCount: 223,
    watchedAll: false,
    rating: 6,
    showGenre: ["Animation", "Action", "Adventure", "Family", "Fantasy"],
  },
];
